#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install nginx locales
sudo unlink /etc/nginx/sites-enabled/default
sudo locale-gen en_US.UTF-8
sudo mkdir /etc/nginx/ssl
sudo echo "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzAvT2pvL1htRUhoTHYKTDd6amlRQVpMQmVsOUdDV3NYWGlQeFdJTWRkUXI4WkdROXFQc2Q0b3duaDNmYkJVSGxER0lkUGNDNWFOdDBCUgplZE44Y05RK0Q5L3lXelRUdnFBa0drcHJYRnlrTTZHc0FMWlBWUFl3Snd5Vms3N0todnpxeEdXWS9EN2hmU0xUCm5IdTM0NVVFRnI3THlOZ2ROVS9hbWM3UVRDQTVJMURCcGpPbnFvT2JtT2Fic0NsQUpZMmRkbmJhZDZHaWwzKzYKTXIveGxkQ0ZaUGVsbVJjWS9wb0xDaGRva2xybDhzS1g3M2lZbkkvalpSQ0VEOEF3S2FUQTRrbGs1TXRCd2RUeQpTWGszN2RYYUFhbWZ2OXpaNVZrVDNudkIwU0xYQ0JDeHEwQXUrSEkwNlNseGYvYXZ5eDdVb3JlYUI0M1pOcFpEClM3bFRPc3VKQWdNQkFBRUNnZ0VCQUlDV0YxeEJpbTRsZDhwY0hsV0Nab0Y3NUNsU0lMV3Z5MU05QXExS3kvRlYKa1FjbStrZVJWWWViOHo3aUc3OEg4dGR4L1RXZlBnM2RubUxFclU4Q1VxanRXbXkwQkNwVWl5NWJSM2hUbkxaRQp3SjZWdXZGT0tjTTRXeWFDVzlGRWFyalpaRjEzQ2EzbTNER0FRaDM2SVV0UVphb2ZQZnd5ZmxPUFozSnlRNHFUCnExVTc5eTgvSzlqdDV1b1VWODBteC9ydmRVbmx5aW5WWXN4UiswakpIekNJQ0F2YnoxMWZUNjFvNGcvZXYyaDUKaGdTK1prK1Nyb3lwcGNxRnF6RTh2dmZITzRleUl5V2svS3dDSDJJWGJRZE5rby9Mc1hQZlpFeGQrSGVsOG00WgpWeXJPckFvcmhmR0dLS2xDNEZQTi9TM3J3MzNnQ0tvK1BzN01Zd0txNzZrQ2dZRUE3YW9aZTRrM0EvREMxL1pGCkJiaHFzd2YyRGJBTnA0NVNGQUd1bURmUVBYSFZZU3dIdTJTMkFieG5vS2tNVHN5QS9IV1N1bThXdWVzK04vbmwKS1JSdjdoQUdyYWdIODdXTXJDRy9BZE5IRHhQM1RIaWhBREU4aHRxb05zOGgyS2ZkMGdEb0MwcXY4MzRqRUZMcworb2VlV3VoOGZqVlM0alZyQ1hCSmpkRlFzYmNDZ1lFQXd2TnhQNms5NjNOUmVtdEExbVU0a09EMXVoUVdBcWlBClB4UUlUQ0Vub0hYbk9UVGw0N0tJRHdHSnR1MmRZb3MvdEw5NDNYSThCNFYySUF2ZVJKbUNrLzdNQ3F3Vm53U2EKWmhHQVhVUHBZbmFYSmNlc1R3MjFlZ3dTVVlwbFFLN3czRDNkZ1MyUVJBNFgzVEdrMkV1QTZibytiZ2lkdC9uVgpvNE95dHBkYmJMOENnWUVBdjJKV0NQUXpPRm9lSFZqMHRpbU95c0xqY3B4T01wcmFIOEJHLzg4YVF4Q3krd0JBCjdiZXBGWGJKb0VmaFlHY3dpNXlHWHRsc1hLVkNRa05iTlp4K2toK1hzU241MVZoaWdvN2VTTE1CcXZPeUZvT2gKYXcwN0o0RlhLbVBjWnFLdmJ4aEp4Q1lOMEsvSHZySjRvVHFxMjV3Ui9IUW1YWUVVdzlJSGVVdVFocnNDZ1lBUgpqQzRXWjlwdDlneFFjNVQ3ZDFMM0gzaWV6aTRKQVRmQjljQ2xjWnFLZy9KVElPTE1jd1p5SzFaRkEvQlZyV2tICmtQQ0ZKa0ltL3lsWnl4ZXZudzIwMm90dExuNG51UmRZdHB5U1NJbWFWa2hXbXpsMFNDeWNscmVUWlZ5bHpObGIKU2FwRmRWOTE4THJQS3lmR1hFMTNQRTlnUWlCSUxoRy96UnZwK1llK0t3S0JnRDdxc3BURmUrajdQSktqT3FMMwordm1VZkhMZUNvNE1aa1I4Q2thS1FGclFLMk1LRE5zeUNzbURVVFIwUU1xczA5aWdSaVFobXg2NklhT2xVRG1yCklDeWNTMVkrdEFZeFZndmR2V3FlL0svWWcxWGlEdHY3eUlqVUd2alVXSjlseVVNUjV4VUVDdTVRYnpHS21LOFMKWTFRNXphOVMyZEFBRndjZmZGYk9BUUNmCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=" | base64 -d > /etc/nginx/ssl/nginx.key
sudo echo "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZRENDQWtpZ0F3SUJBZ0lKQUxPdkNGNmJ5dk41TUEwR0NTcUdTSWIzRFFFQkN3VUFNRVV4Q3pBSkJnTlYKQkFZVEFrRlZNUk13RVFZRFZRUUlEQXBUYjIxbExWTjBZWFJsTVNFd0h3WURWUVFLREJoSmJuUmxjbTVsZENCWAphV1JuYVhSeklGQjBlU0JNZEdRd0hoY05NVGd3T0RFM01Ua3lPREU0V2hjTk1Ua3dPREUzTVRreU9ERTRXakJGCk1Rc3dDUVlEVlFRR0V3SkJWVEVUTUJFR0ExVUVDQXdLVTI5dFpTMVRkR0YwWlRFaE1COEdBMVVFQ2d3WVNXNTAKWlhKdVpYUWdWMmxrWjJsMGN5QlFkSGtnVEhSa01JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXRQem82UDE1aEI0Uzd5Kzg0NGtBR1N3WHBmUmdsckYxNGo4VmlESFhVSy9HUmtQYWo3SGVLTUo0CmQzMndWQjVReGlIVDNBdVdqYmRBVVhuVGZIRFVQZy9mOGxzMDA3NmdKQnBLYTF4Y3BET2hyQUMyVDFUMk1DY00KbFpPK3lvYjg2c1JsbVB3KzRYMGkwNXg3dCtPVkJCYSt5OGpZSFRWUDJwbk8wRXdnT1NOUXdhWXpwNnFEbTVqbQptN0FwUUNXTm5YWjIybmVob3BkL3VqSy84WlhRaFdUM3Baa1hHUDZhQ3dvWGFKSmE1ZkxDbCs5NG1KeVA0MlVRCmhBL0FNQ21rd09KSlpPVExRY0hVOGtsNU4rM1YyZ0dwbjcvYzJlVlpFOTU3d2RFaTF3Z1FzYXRBTHZoeU5Pa3AKY1gvMnI4c2UxS0szbWdlTjJUYVdRMHU1VXpyTGlRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVWeEwvOC9pSApBdFYwT3VDalNBUktqK0NwMHJnd0h3WURWUjBqQkJnd0ZvQVVWeEwvOC9pSEF0VjBPdUNqU0FSS2orQ3Awcmd3CkR3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUhBUGg1VUgxWFVQWjJENm8KNVpLSzRmWkVvNnJWYzdSQ2s0UlVNbjdkeGcvNUJnWG1HcVlWMDduZzRySFFUejBsYWwyNXViZTBsQlBCNDcwSQphVTVuVkJkM0JqWTBmL2dJeWxNSjgvQWdDQk4rYWN5RkR5NTY3Mk0rY1hWblhRSFAvNkVrejdSYmVncVZTTnpNCmc2dVR0RjUvWGtQbzhjajNZQVFzRWU5dXBuT21CdjlETE42RGxudDR2UkZ1K21QbUVZWkx0MjFoa2FzbFNlNmIKdnhpaGphdXNyOUVvTUZ5amF2K24wZVdmZmUvQVd2T1pkOS9qQnhwTEIxUnZqQUlTdW5ZdmorRWJtQWRJVURyYQpjTnJWeVJtZENZN0toTTFFZitMbGZvakk0bDJ6ZnRCcnJPbmZKcTBzZStNS2crcVRMWVZYTXFHNWNUeEdMc2tICmdTaEVwdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=" | base64 -d > /etc/nginx/ssl/nginx.crt
sudo cat << EOF > /etc/nginx/sites-enabled/web-app
server {
    listen 80;
    charset utf-8;
    resolver 169.254.169.253;
    location / {
        proxy_set_header HOST \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        set \$dynamic_nginx_variable "http://${service_name}.${sd_ns_name}:8080";
        proxy_pass \$dynamic_nginx_variable;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
    }
}
server {
    listen 443 ssl;
    charset utf-8;
    resolver 169.254.169.253;
    ssl_certificate     /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    location / {
        proxy_set_header HOST \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        set \$dynamic_nginx_variable "http://${service_name}.${sd_ns_name}:8080";
        proxy_pass \$dynamic_nginx_variable;
        proxy_buffer_size          128k;
        proxy_buffers              4 256k;
        proxy_busy_buffers_size    256k;
    }
}
EOF
sudo systemctl restart nginx
sudo systemctl enable nginx